company_admin:
    resource: "@CompanyAdminBundle/Resources/config/routing.yml"
    prefix:   /

company_company:
    resource: "@CompanyCompanyBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
