security:
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Company\AdminBundle\Entity\User: plaintext

    providers:
        main:
            entity:
                class: Company\AdminBundle\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: true
            provider: main
            form_login:
                login_path: login   
                check_path: login_check
                default_target_path: company_admin_homepage
            logout:
                path: logout
                target: login

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
